In [1]:
import numpy as np

np.__version__

'2.0.1'

In [2]:
# 用()和[]都行
n1 = np.array([1, 2, 3])
n2 = np.array(((1, 2, 3), (4, 5, 6)))
n3 = np.array([[1, 2, 3], [4, 5, 6]])
n1, n2, n3

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [4]:
x, y = np.zeros((3, 4)), np.array([1, 2, 3])
x, y, x.dtype, y.dtype

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([1, 2, 3]),
 dtype('float64'),
 dtype('int64'))

In [5]:
n = np.arange(6)
n, n.reshape(2, 3)

(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [6]:
np.ones((2, 3)), np.full((2, 3), 2)  # ones就是用1去full

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2, 2],
        [2, 2, 2]]))

索引的使用

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6.0]])
a[-2:, 1:3]

array([[2., 3.],
       [5., 6.]])

广播机制

In [17]:
c = np.array(93)  # 单个数
a,c

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array(93))

In [18]:
a + c, a - c, a * c, a / c

(array([[94., 95., 96.],
        [97., 98., 99.]]),
 array([[-92., -91., -90.],
        [-89., -88., -87.]]),
 array([[ 93., 186., 279.],
        [372., 465., 558.]]),
 array([[0.01075269, 0.02150538, 0.03225806],
        [0.04301075, 0.05376344, 0.06451613]]))

In [19]:
a_origin = np.copy(a)
b = np.copy(a)
a[np.arange(2), 1] += 100  # <=> a[[0,1],1]触发广播 => a[0,1] += 100, a[1,1] += 100
b[np.arange(2), np.arange(2)] += 100  # 一一对应 => a[0,0] += 100, a[1,1] += 100
a_origin, a, b

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[  1., 102.,   3.],
        [  4., 105.,   6.]]),
 array([[101.,   2.,   3.],
        [  4., 105.,   6.]]))

In [20]:
a > 10

array([[False,  True, False],
       [False,  True, False]])

转换类型

In [22]:
# `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.
a = np.array([[-1, 0, 3], [4, 5, 6]], dtype=np.bytes_)
(a, a.dtype, a.astype(np.int32), a.astype(np.float32),
 a.astype(np.float32).astype(np.bytes_))
#, a.astype(np.bool) # 可以转会警告,=0为False

(array([[b'-1', b'0', b'3'],
        [b'4', b'5', b'6']], dtype='|S2'),
 dtype('S2'),
 array([[-1,  0,  3],
        [ 4,  5,  6]], dtype=int32),
 array([[-1.,  0.,  3.],
        [ 4.,  5.,  6.]], dtype=float32),
 array([[b'-1.0', b'0.0', b'3.0'],
        [b'4.0', b'5.0', b'6.0']], dtype='|S32'))