In [1]:
import numpy as np
"""随机数"""
# np.random.random((2, 3)) # 这是旧版, 已经不推荐
seed = 2025
rng = np.random.default_rng(seed)
rng.random((2, 3)), rng.random((2, 3))  # 每次随机都使用前一个种子

(array([[0.99445781, 0.38200974, 0.82714801],
        [0.83725528, 0.97580901, 0.07722503]]),
 array([[0.31745641, 0.91955541, 0.67586956],
        [0.28582494, 0.38954302, 0.23021956]]))

In [2]:
# np.random.randint(5, size = (2, 3))  # 旧版, 不推荐
r1 = rng.integers(10, size=(4, 1))
r2 = rng.integers(100, size=(2, 3))  # 随机序列也是固定的
r1, r2

(array([[7],
        [1],
        [4],
        [1]]),
 array([[34, 97, 66],
        [42, 21,  6]]))

In [3]:
from copy import copy

# shuffle不会返回值,是一个void函数, 只会把输入的数组打乱
a = np.arange(10)
a_copy = copy(a)
b = rng.shuffle(a)
a_copy, b, a

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 None,
 array([5, 2, 3, 8, 6, 9, 4, 7, 0, 1]))

In [4]:
a = np.array([[1, 2, 3], [3, 2, 9]])
# np.random.choice(a.reshape(-1), size=(2, 3))  # a must be 1-dimensional
rng.choice(a, size=(2, 3, 4), replace=True)
# 没有这个限制啦 (must be 1-dimensional)

array([[[[3, 2, 9],
         [3, 2, 9],
         [3, 2, 9],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [3, 2, 9]]],


       [[[3, 2, 9],
         [3, 2, 9],
         [3, 2, 9],
         [3, 2, 9]],

        [[3, 2, 9],
         [3, 2, 9],
         [3, 2, 9],
         [1, 2, 3]],

        [[1, 2, 3],
         [3, 2, 9],
         [3, 2, 9],
         [1, 2, 3]]]])

where和nonzero

nonzero: 返回非零元素的下标

In [5]:
a = np.array([0, 1, 999])
b = np.array([[0, 1, 999], [100, 999, 999], [0, -1, 999]])
np.nonzero(a == 999), np.nonzero(b == 999), type(np.nonzero(a == 999))
# 返回符合条件的元素的位置,用一维数组表示各个维度对应的下标
# 比如这里的返回结果表示: a[0,2] == 999, a[1,1] == 999, ...
# 注意!返回的是一个存储一维数组的元组，不是一个array!

((array([2]),), (array([0, 1, 1, 2]), array([2, 1, 2, 2])), tuple)

where: 返回非零元素的下标


In [6]:
# np.where(cond, x, y) 返回满足条件的元素, 否则返回另一个数组的元素
a = np.array([[1, 2], [100, 4]])
b = np.array([[0, 0], [0, 0]])
a, b, np.where(a > 99, a, b)  # 形状不变

(array([[  1,   2],
        [100,   4]]),
 array([[0, 0],
        [0, 0]]),
 array([[  0,   0],
        [100,   0]]))

In [7]:
np.where(a >= 2)  # 不推荐
# np.where(cond)退化为np.nonzero(cond) 与 np.where(cond, x, y)截然不同, 不推荐

(array([0, 1, 1]), array([1, 0, 1]))