数组运算

In [2]:
import numpy as np

seed = 2025
rng = np.random.default_rng(seed)
x = rng.random((2, 5))
x, np.sum(x), np.average(x), np.mean(x)

(array([[0.99445781, 0.38200974, 0.82714801, 0.83725528, 0.97580901],
        [0.07722503, 0.31745641, 0.91955541, 0.67586956, 0.28582494]]),
 np.float64(6.292611191218889),
 np.float64(0.6292611191218889),
 np.float64(0.6292611191218889))

整块复制

In [3]:
np.tile(x, (2, 2))

array([[0.99445781, 0.38200974, 0.82714801, 0.83725528, 0.97580901,
        0.99445781, 0.38200974, 0.82714801, 0.83725528, 0.97580901],
       [0.07722503, 0.31745641, 0.91955541, 0.67586956, 0.28582494,
        0.07722503, 0.31745641, 0.91955541, 0.67586956, 0.28582494],
       [0.99445781, 0.38200974, 0.82714801, 0.83725528, 0.97580901,
        0.99445781, 0.38200974, 0.82714801, 0.83725528, 0.97580901],
       [0.07722503, 0.31745641, 0.91955541, 0.67586956, 0.28582494,
        0.07722503, 0.31745641, 0.91955541, 0.67586956, 0.28582494]])

.argsort(),将元素按照行从小到大排序，返回对应位置元素的下标

In [4]:
x.argsort()

array([[1, 2, 3, 4, 0],
       [0, 4, 1, 3, 2]])

In [14]:
a = np.array([[[1, 6, 1], [3, 4, 5]], [[99, 6, 1], [3, 4, 5]]])
np.argsort(a, axis=0), np.argsort(a, axis=1), np.argsort(a, axis=2)
# 形状不变

(array([[[0, 0, 0],
         [0, 0, 0]],
 
        [[1, 1, 1],
         [1, 1, 1]]]),
 array([[[0, 1, 0],
         [1, 0, 1]],
 
        [[1, 1, 0],
         [0, 0, 1]]]),
 array([[[0, 2, 1],
         [0, 1, 2]],
 
        [[2, 1, 0],
         [0, 1, 2]]]))

row_stack按行拼接 (扩充行)，column_stack (扩充列)  (这是旧版, 不推荐)

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6.0]])
b = np.array([[7, 8, 9], [10, 11, 12]])
np.row_stack((a, b)), np.column_stack((a, b))

/var/folders/ts/l6y5qty97dzg1gcwdg_5pv080000gn/T/ipykernel_72040/4138378578.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b)), np.column_stack((a, b))


(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]),
 array([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]]))

新版使用 vstack和hstack

In [6]:
np.vstack((a, b)), np.hstack((a, b))

(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]),
 array([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]]))

逐元素计算

In [7]:
a + b, a - b, a * b, a / b

(array([[ 8., 10., 12.],
        [14., 16., 18.]]),
 array([[-6., -6., -6.],
        [-6., -6., -6.]]),
 array([[ 7., 16., 27.],
        [40., 55., 72.]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

矩阵乘法 (记得保证col_a = row_b) 三种写法

In [9]:
# 下面两种写法等价, 返回新的ndarray
np.dot(a, b.T), a @ b.T

(array([[ 50.,  68.],
        [122., 167.]]),
 array([[ 50.,  68.],
        [122., 167.]]))

In [11]:
# 第三种写法, 先转换为矩阵类型, 这里*就是矩阵乘法了,不过注意: 返回的是矩阵matrix类型
# np.mat(a) * np.mat(b.T) # AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.
np.asmatrix(a) * np.asmatrix(b.T)

matrix([[ 50.,  68.],
        [122., 167.]])

求逆 (输入若不可逆会报错Singular matrix)

In [12]:
np.linalg.inv(a @ a.T), np.linalg.inv(np.array([[1]]))
# np.linalg.inv(np.array([[1, 0], [0, 0]])))

(array([[ 1.42592593, -0.59259259],
        [-0.59259259,  0.25925926]]),
 array([[1.]]))

np.argmax 返回最大值的下标

In [13]:
a = np.array([[[1, 6, 1], [3, 4, 5]], [[99, 6, 1], [3, 4, 5]]])
np.argmax(a, axis=0), np.argmax(a, axis=1), np.argmax(a, axis=2)
# 总共0,1,2三维, axis=多少就是把哪个维度消掉
# 比如axis=0,则shape(2,2,3)->(2,3)
# 比如axis=1,则shape(2,2,3)->(2,3)
# 比如axis=2,则shape(2,2,3)->(2,2)

array([[False, False, False],
       [False, False, False]])

linspace 生成等差数列

In [15]:
np.linspace(100,500,6)

array([100., 180., 260., 340., 420., 500.])

.eye(n) 创建单位矩阵

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])