In [17]:
import torch
torch.__version__

'2.5.1'

In [1]:
device = ""
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"  # macOS m1 的 mps ≈ NVIDIA 1050Ti
else:
    device = "cpu"
# 每次setting里更改本地或远程的解释器, 看这里是cuda还是mps就知道有没有切成功了
# 现在每次都得重新打开项目,才切换
print(f"Using {device} device")

Using mps device


In [6]:
x = torch.arange(12)
x,x.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]))

In [4]:
# num of elements
x.numel()

12

In [7]:
x.reshape(2, 3, -1) ,x.reshape(3, -1)

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [8]:
torch.zeros((2, 3)),torch.ones(2)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([1., 1.]))

In [14]:
t0 = torch.tensor(1)
t1 = torch.tensor([[1, 2, 3], [2, 0, 0]])
t0.dtype,t1.dtype  # 默认都是long(即int64)

(torch.int64, torch.int64)

In [15]:
# 可以手动赋值创建
x = torch.tensor([[1, 2, 3], [2, 0, 0.]])
y = torch.tensor([[1, 2, 3], [2, 0, 0.9]]).type(torch.long)
x, x.shape, x.dtype,y, y.shape, y.dtype

(tensor([[1., 2., 3.],
         [2., 0., 0.]]),
 torch.Size([2, 3]),
 torch.float32,
 tensor([[1, 2, 3],
         [2, 0, 0]]),
 torch.Size([2, 3]),
 torch.int64)

类型转换

In [16]:
x.type(torch.int64), x.int()  # 此二法,基本等价,细微差别

(tensor([[1, 2, 3],
         [2, 0, 0]]),
 tensor([[1, 2, 3],
         [2, 0, 0]], dtype=torch.int32))

In [18]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

其他

In [19]:
a = torch.arange(12)
print(a)
b = a.reshape(3, 4)
b[:] = 2
print(a)  # 注意: a的值也被改变了

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
