In [1]:
import torch
torch.__version__

'2.5.1'

随机数

torch.manual_seed(2025) # 可固定seed

In [2]:
torch.manual_seed(2025) # 可固定seed
torch.randn((2, 3, 4))

tensor([[[-1.1607, -1.5591,  0.7782, -0.9990],
         [-0.3729, -0.1594,  0.2836, -1.1234],
         [-1.1871, -0.2822, -0.2651,  2.7671]],

        [[ 0.8749, -0.1597, -1.5970, -0.7229],
         [ 0.9320, -0.7882, -2.8070,  0.5447],
         [-1.6047,  0.2632, -1.9616, -0.9576]]])

幂运算

In [3]:
x = torch.tensor([1.0, 2, 3, 4])
y = torch.tensor([4, 3, 3, 3])
x + y, x - y, x * y, x / y, x ** y  # **是幂运算

(tensor([5., 5., 6., 7.]),
 tensor([-3., -1.,  0.,  1.]),
 tensor([ 4.,  6.,  9., 12.]),
 tensor([0.2500, 0.6667, 1.0000, 1.3333]),
 tensor([ 1.,  8., 27., 64.]))

In [4]:
torch.exp(x)  # e的x次幂

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

tensor连结

In [7]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor(([2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]))
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dim=0 表示在行上拼接(增加行),dim=1 表示在列上拼接(增加列)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [8]:
X == Y, X > Y, X < Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

聚合函数, 生成单元素tensor

In [9]:
X.sum(), X.int(), Y.prod()

(tensor(66.),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], dtype=torch.int32),
 tensor(13824.))

广播机制(broadcast mechanism)按元素操作

In [10]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
a + b  # 维度一致,均扩成3x2,缺失的行列复制已有的

tensor([[0, 1],
        [1, 2],
        [2, 3]])

元素查询,切片

In [12]:
X, X[1, 2], X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(6.),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

元素赋值

In [13]:
X[0:2, :] = 666
X[1, 2] = 777
X

tensor([[666., 666., 666., 666.],
        [666., 666., 777., 666.],
        [  8.,   9.,  10.,  11.]])

In [14]:
# 一些操作会导致为新结果分配内存
before = id(Y)
Y = Y + X  # 如果用Y[:]=Y+X或者Y+=X , 则不会重新分配内存
id(Y) == before

False

原地操作

In [15]:
Z1 = torch.zeros_like(Y)
Z2 = torch.zeros_like(Y)
before1 = id(Z1)
before2 = id(Z2)
Z1[:] = Z1 + X
Z2 += X
id(Z1) == before1, id(Z2) == before2

(True, True)