pytorch的tensor与numpy之间的一些操作

In [1]:
import numpy as np
import torch
np.__version__, torch.__version__

(<module 'numpy.version' from '/Users/chenyun/anaconda3/envs/p31225/lib/python3.12/site-packages/numpy/version.py'>,
 '2.5.1')

转换

In [3]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
A = X.numpy()
B = torch.tensor(A)
X,A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [4]:
type(X),type(A), type(B)

(torch.Tensor, numpy.ndarray, torch.Tensor)