In [4]:
import torch
import torch.nn as nn

softmax = nn.Softmax()
sigmoid = nn.Sigmoid()
relu = nn.ReLU()
leaky_relu = nn.LeakyReLU()

(
    softmax(torch.tensor(3.0)),
    softmax(torch.tensor([[0, 0, 1], [1, 0, 2.0]])),
    softmax(torch.tensor([[2, 1, 1], [1, 3, 3.0]])),
    softmax(torch.tensor([[20, 10, 10], [10, 30, 30.0]])),
    torch.tensor([[3.0, 9999], [123, 234]]).shape,
    softmax(torch.tensor([[3.0, 9999], [123, 234]])),
    softmax(torch.tensor([[3.0, 222], [123, 234]])),
    softmax(torch.tensor([[3.0, 3], [233, 234]])),
    softmax(torch.tensor([[3.0, 9999], [233, 234]])),
    softmax(torch.tensor([[[3.0, 9999], [233, 234]]])),
    torch.tensor([[[233, 234], [233, 234]], [[3.0, 9999], [233, 234]]]).shape,
    softmax(torch.tensor([[[233, 234], [233, 234]], [[3.0, 9999], [233, 234]]])),
)

(tensor(1.),
 tensor([[0.2119, 0.2119, 0.5761],
         [0.2447, 0.0900, 0.6652]]),
 tensor([[0.5761, 0.2119, 0.2119],
         [0.0634, 0.4683, 0.4683]]),
 tensor([[9.9991e-01, 4.5396e-05, 4.5396e-05],
         [1.0306e-09, 5.0000e-01, 5.0000e-01]]),
 torch.Size([2, 2]),
 tensor([[0., 1.],
         [0., 1.]]),
 tensor([[0., 1.],
         [0., 1.]]),
 tensor([[0.5000, 0.5000],
         [0.2689, 0.7311]]),
 tensor([[0.0000, 1.0000],
         [0.2689, 0.7311]]),
 tensor([[[1., 1.],
          [1., 1.]]]),
 torch.Size([2, 2, 2]),
 tensor([[[1.0000, 0.0000],
          [0.5000, 0.5000]],
 
         [[0.0000, 1.0000],
          [0.5000, 0.5000]]]))

$$
\operatorname{softmax}(\operatorname{input}[0])=\frac{e^{\operatorname{logit}}}{\sum e^{\log \mid t s}}=\left[\frac{e^0}{e^0+e^0+e^1}, \frac{e^0}{e^0+e^0+e^1}, \frac{e^1}{e^0+e^0+e^1}\right]
$$

In [8]:
(
    sigmoid(torch.Tensor([0])),
    sigmoid(torch.Tensor([2])),
    sigmoid(torch.Tensor([999])),
    sigmoid(torch.Tensor([0, 2, 999]))
)

(tensor([0.5000]),
 tensor([0.8808]),
 tensor([1.]),
 tensor([0.5000, 0.8808, 1.0000]))

In [16]:
(relu(torch.Tensor([-1, 2, 999])).int(),
 relu(torch.Tensor([-99, 2, 999])).int(),
 leaky_relu(torch.Tensor([-1, 2, 999])).int(),
 leaky_relu(torch.Tensor([-999, 2, 999])).int(),
 leaky_relu(torch.Tensor([-99999, 2, 999])).int(),
 )

(tensor([  0,   2, 999], dtype=torch.int32),
 tensor([  0,   2, 999], dtype=torch.int32),
 tensor([  0,   2, 999], dtype=torch.int32),
 tensor([ -9,   2, 999], dtype=torch.int32),
 tensor([-999,    2,  999], dtype=torch.int32))